// <auto-generated />
namespace Photographers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddRolles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRolles));
        
        string IMigrationMetadata.Id
        {
            get { return "201703102050519_AddRolles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
